<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">
  <title>SB Admin - Start Bootstrap Template</title>
  <!-- Bootstrap core CSS-->
  <link href="vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">
  <!-- Custom fonts for this template-->
  <link href="vendor/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css">
  <!-- Custom styles for this template-->
  <link href="theme/css/sb-admin.css" rel="stylesheet">
  <!-- css modify for override class -->
  <link href="theme/css/sb-admin-override.css" rel="stylesheet">

  <style>
  .w-row-100{

  }
  .text-white{
    color: white;
  }

  .text-Logo{
    font-size: 50px;
  }

  .bg-white{
    background-color: #fff;
  }

  html, body {
    height: 100%;
  }

  /*sm*/
  @media (max-width: 576px) { 
    .text-Logo {
      font-size: 40px!important;
    }
    .h-100{
      height: unset;
    }
    #form-login{
      -ms-flex-align: unset!important;
      align-items: unset!important;
      -ms-flex-pack: unset!important;
      justify-content: unset!important;
    }
  }

  /*md*/
  @media (min-width: 768px) {
    .text-Logo {
      font-size: 90px!important;
    }
    .h-100{
      height: 25%!important;
    }
  }

  /*lg*/
  @media (min-width: 992px) {
    .text-Logo {
      font-size: 70px!important;
    }
    .h-100{
      height: 25%!important;
    }
  }

  /*xl*/
  @media (min-width: 1200px) {
    .text-Logo {
      font-size: 110px!important;
    }
    .h-100{
      height: 100%!important;
    }
  }

</style>

</head>

<body class="bg-dark">

  <div class="container-fluid h-100">

    <div class="row h-100">
      <div class="col-xl-9 col-lg-9 col-md-12 col-sm-12 col-xs-12 d-flex align-items-center justify-content-center bg-dark text-white">
        <div class="text-Logo">
          <i class="fa fa-fw fa-map-pin"></i> 
          SML TOOLS
        </div>
      </div>

      <div class="col-xl-3 col-lg-12 col-md-12 col-sm-12 col-xs-12 bg-white d-flex align-items-center justify-content-center" id="form-login">
        <form class="w-100 mt-5 mb-5" action="dashboard.php">
          <h2 class="text-center mb-3">Login</h4>
            <div class="form-group">
              <label for="exampleInputEmail1">Email address</label>
              <input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Enter email">
            </div>
            <div class="form-group">
              <label for="exampleInputPassword1">Password</label>
              <input type="password" class="form-control" id="exampleInputPassword1" placeholder="Password">
            </div>
            <div class="form-check">
              <label class="form-check-label">
                <input type="checkbox" class="form-check-input">
                Remember Password
              </label>
            </div>
            <button type="submit" class="btn btn-primary btn-block">Login</button>
            <div class="text-center">
              <a class="d-block small mt-3" href="register.html">Register an Account</a>
              <a class="d-block small" href="forgot-password.html">Forgot Password?</a>
            </div>
          </form>
        </div>

      </div>

      <!-- Bootstrap core JavaScript-->
      <script src="vendor/jquery/jquery.min.js"></script>
      <script src="vendor/popper/popper.min.js"></script>
      <script src="vendor/bootstrap/js/bootstrap.min.js"></script>
      <!-- Core plugin JavaScript-->
      <script src="vendor/jquery-easing/jquery.easing.min.js"></script>
    </body>

    </html>
