<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">
  <title>Create Project</title>
  <!-- Bootstrap core CSS-->  
  <link href="../vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">
  <!-- Custom fonts for this template-->
  <link href="../vendor/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css">
  <!-- Custom styles for this template-->
  <link href="../theme/css/sb-admin.css" rel="stylesheet">
  <!-- css modify for override class -->
  <link href="../theme/css/sb-admin-override.css" rel="stylesheet">
</head>

<body class="fixed-nav sticky-footer bg-dark" id="page-top">

  <!-- Navigation-->
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top" id="mainNav">

    <!-- Logo -->
    <a class="navbar-brand" href="#"><i class="fa fa-fw fa-map-pin"></i> SML TOOLS</a>
    <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <!-- Menu -->
    <div class="collapse navbar-collapse" id="navbarResponsive">
      <ul class="navbar-nav navbar-sidenav" id="exampleAccordion">

        <li class="nav-item mb-1">
          <form class="form-inline">
            <div class="input-group ml-2 mr-2 mt-sm-0 mt-3" style="width: 100%!important;">
              <input class="form-control" type="text" placeholder="Search Project...">
            </div>
          </form>
        </li>



        <li class="nav-item" data-toggle="tooltip" data-placement="right" title="Dashboard">
          <a class="nav-link" href="#">
            <i class="fa fa-fw fa-dashboard"></i>
            <span class="nav-link-text">Dashboard</span>
          </a>
        </li>
        <li class="nav-item" data-toggle="tooltip" data-placement="right" title="Collaboration Setting">
          <a class="nav-link" href="../task/collaburation.php">
            <i class="fa fa-fw fa-dashboard"></i>
            <span class="nav-link-text">Collaboration Setting</span>
          </a>
        </li>
        <li class="nav-item" data-toggle="tooltip" data-placement="right" title="Stakeholder">
          <a class="nav-link" href="stakeholder.php">
            <i class="fa fa-fw fa-dashboard"></i>
            <span class="nav-link-text">Stakeholder</span>
          </a>
        </li>
        <li class="nav-item" data-toggle="tooltip" data-placement="right" title="Resource">
          <a class="nav-link" href="resource.php">
            <i class="fa fa-fw fa-dashboard"></i>
            <span class="nav-link-text">Resource</span>
          </a>
        </li>
        
        
      </ul>
      <ul class="navbar-nav sidenav-toggler">
        <li class="nav-item">
          <a class="nav-link text-center" id="sidenavToggler">
            <i class="fa fa-fw fa-angle-left"></i>
          </a>
        </li>
      </ul>

      <!-- Profile Dropdown -->
      <ul class="navbar-nav ml-auto">
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <i class="fa fa-fw fa-user"></i>Account
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
            <h6 class="dropdown-header">Profile Setting:</h6>
            <a class="dropdown-item" href="#">Edit Profile</a>
            <a class="dropdown-item" href="#">Change Password</a>
          </div>
        </li>
        <!-- Logout btn -->
        <li class="nav-item">
          <a class="nav-link" data-toggle="modal" data-target="#exampleModal">
            <i class="fa fa-fw fa-sign-out"></i>Logout</a>
          </li>
        </ul>

      </div>
    </nav>

    <!-- Content Body -->
    <div class="content-wrapper">

      <!-- Page Header -->
      <div class="page-header">
        <div class="container-fluid">

          <h1 class="inline">Create Project</h1>
          <!-- Breadcrumbs-->
          <ol class="breadcrumb inline-flex">
            <li class="breadcrumb-item">
            	<a href="../dashboard.php">
            		Dashboard
            	</a>
            </li>
            <li class="breadcrumb-item">
            	Create Project
            </li>
          </ol>
          
           <!-- Content Page -->
        <div class="row">
          <div class="col-12 mb-4">
            <div class="card">
              <div class="card-body">
                <div class="">
                <!-- container -->
                  <form>
                    <div class="form-group row">
                      <label for="project" class="col-sm-2 col-form-label">Project Name</label>
                      <div class="col-sm-6">
                        <input type="text" class="form-control" id="projectname" placeholder="Project Name">
                      </div>
                    </div>
                    <div class="form-group row">
                      <label for="project" class="col-sm-2 col-form-label">Description</label>
                      <div class="col-sm-6">
                      	<textarea id="description" class="form-control" id="description" rows="3"></textarea>
                      </div>
                    </div>
                    <div class="form-group row">
				      <div class="offset-sm-2 col-sm-10">
				        <button type="submit" class="btn btn-primary" id="saveproject" >Save</button>
				      </div>
				    </div>
                  </form>
                </div>
              </div>
            </div>
          </div>

        </div>

      	<!-- /.container-->
        </div>
      </div> 
      <!-- /.Page Header -->


      <!-- Footer -->
      <footer class="sticky-footer">
        <div class="container">
          <div class="text-center">
            <small>Copyright Your Website 2017</small>
          </div>
        </div>
      </footer>
      <!-- /.Footer -->

      <!-- Scroll to Top Button-->
      <a class="scroll-to-top rounded" href="#page-top"><i class="fa fa-angle-up"></i></a>
      <!-- /.Scroll to Top Butto-->

      <!-- Logout Modal-->
      <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title" id="exampleModalLabel">Ready to Leave?</h5>
              <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">×</span>
              </button>
            </div>
            <div class="modal-body">Select "Logout" below if you are ready to end your current session.</div>
            <div class="modal-footer">
              <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
              <a class="btn btn-primary" href="login.html">Logout</a>
            </div>
          </div>
        </div>
      </div>
      <!-- /.Logout Modal-->
      
      <!-- Bootstrap core JavaScript-->
      <script src="../vendor/jquery/jquery.min.js"></script>
      <script src="../vendor/popper/popper.min.js"></script>
      <script src="../vendor/bootstrap/js/bootstrap.min.js"></script>
      <!-- Core plugin JavaScript-->
      <script src="../vendor/jquery-easing/jquery.easing.min.js"></script>
      <!-- Custom scripts for all pages-->
      <script src="../theme/js/sb-admin.min.js"></script>
      <!-- /.Bootstrap core JavaScript-->

      <script type="text/javascript">
        $(function () {
          $('[data-toggle="popover"]').popover()
        })
      </script>

    </div>
    <!-- /.content-wrapper-->
    <!-- /.End Page -->

  </body>

  </html>
