<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">
  <title>Dashboard</title>
  <!-- Bootstrap core CSS-->  
  <link href="vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">
  <!-- Custom fonts for this template-->
  <link href="vendor/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css">
  <!-- Custom styles for this template-->
  <link href="theme/css/sb-admin.css" rel="stylesheet">
  <!-- css modify for override class -->
  <link href="theme/css/sb-admin-override.css" rel="stylesheet">
</head>

<body class="fixed-nav sticky-footer bg-dark" id="page-top">

  <!-- Navigation-->
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top" id="mainNav">

    <!-- Logo -->
    <a class="navbar-brand" href="#"><i class="fa fa-fw fa-map-pin"></i> SML TOOLS</a>
    <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <!-- Menu -->
    <div class="collapse navbar-collapse" id="navbarResponsive">
      <ul class="navbar-nav navbar-sidenav" id="exampleAccordion">

        <li class="nav-item" data-toggle="tooltip" data-placement="right" title="Project: Test System">
          <div class="profile">
            <div class="media">
              <div class="profile-icon">
                <span class="fa-stack fa-2x" role="profile">
                  <i class="fa fa-circle fa-stack-2x text-white"></i>
                  <i class="fa fa-cubes fa-stack-1x"></i>
                </span>
              </div>
              <div class="profile-contant nav-link-text">
               <div class="profile-project-t">
                Project : Test System
              </div>
              <hr class="profile-hr">
              <div class="profile-project-b">
                Developer
              </div>
            </div>
          </div>
          <div class="nav-link" role="profile-input">
            <form>
              <div class="input-group input-group-sm">
                <input type="text" class="form-control" placeholder="Find Project..." aria-label="Project" aria-describedby="sizing-addon2">
              </div>
            </form>              
          </div>
        </li>

        <li class="nav-item" data-toggle="tooltip" data-placement="right" title="Dashboard">
          <a class="nav-link" href="#">
            <i class="fa fa-fw fa-dashboard"></i>
            <span class="nav-link-text">Dashboard</span>
          </a>
        </li>


      </ul>
      <ul class="navbar-nav sidenav-toggler">
        <li class="nav-item">
          <a class="nav-link text-center" id="sidenavToggler">
            <i class="fa fa-fw fa-angle-left"></i>
          </a>
        </li>
      </ul>

      <!-- Profile Dropdown -->
      <ul class="navbar-nav ml-auto">

        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <i class="fa fa-fw fa-user"></i>Account
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
            <h6 class="dropdown-header">Profile Setting:</h6>
            <a class="dropdown-item" href="#">Edit Profile</a>
            <a class="dropdown-item" href="#">Change Password</a>
          </div>
        </li>
        <!-- Logout btn -->
        <li class="nav-item">
          <a class="nav-link" data-toggle="modal" data-target="#exampleModal">
            <i class="fa fa-fw fa-sign-out"></i>Logout</a>
          </li>
        </ul>

      </div>
    </nav>

    <!-- Content Body -->
    <div class="content-wrapper">

      <!-- Page Header -->
      <div class="page-header">
        <div class="container-fluid">
          <div class="pull-right">
            <!-- onclick="$('#filter-product').toggleClass('hidden-sm hidden-xs');" -->
            <button type="button" tooltip="tooltip" data-toggle="tooltip" data-original-title="Filter" 
            class="btn btn-light d-md-none" onclick="$('#filter').toggleClass('d-none');"><i class="fa fa-filter"></i></button>
            <a href="project/create" data-toggle="tooltip" title="" class="btn btn-primary" data-original-title="New Project"><i class="fa fa-plus"></i></a>
          </div>

          <h1 class="inline">Dashboard</h1>
          <!-- Breadcrumbs-->
          <ol class="breadcrumb inline-flex">
            <li class="breadcrumb-item">
             Dashboard
           </li>
         </ol>
       </div>
     </div> 
     <!-- /.Page Header -->

     <div class="container-fluid">
      <div class="row  mb-3">
        <!-- Card Layout -->
        <div class="col-md-9 col-sm-12 order-md-1 order-sm-1 order-2">
          <div class="card">
            <div class="card-body">
              <div class="row">
                <!-- Card -->
                <div class="col-xl-4 col-sm-6 mb-3 small">
                  <div class="card text-white bg-primary o-hidden h-100">
                    <div class="card-body">
                      <div class="card-body-icon">
                        <i class="fa fa-fw fa-cubes"></i>
                      </div>
                      <h6 class="card-title"><a class="card-link text-top-100" href="task/task.php">Questionnaire System</a></h6>
                    </div>
                    <div class="card-footer text-white clearfix small">

                      <!-- btn footter left -->
                      <span class="float-left">
                        <!-- emty -->
                      </span>

                      <!-- btn footer right -->
                      <span class="float-right">
                        <div class="btn-group">
                          <button type="button" class="btn btn-success icon-circle dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"></button>
                          <div class="dropdown-menu" style="z-index:3!important;">
                            <a class="dropdown-item" href="project/edit.php"><i class="fa fa-fw fa-edit"></i> Edit</a>
                            <a data-toggle="modal" title="" data-target="#deleteModal" class="dropdown-item" href="#"><i class="fa fa-fw fa-trash"></i> Delete</a>
                            <a class="dropdown-item" href="project/stakeholder.php"><i class="fa fa-fw fa-users"></i> Stakeholder</a>
                            <a class="dropdown-item" href="project/resourse.php"><i class="fa fa-fw fa-book"></i> Resourse</a>
                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item" href="#"><i class="fa fa-fw fa-info-circle"></i> More Detail</a>
                          </div>
                        </div>
                      </span>
                    </div>
                  </div>
                </div>
                <!-- /.Card -->
                <!-- Card -->
                <div class="col-xl-4 col-sm-6 mb-3 small">
                  <div class="card text-white bg-primary o-hidden h-100">
                    <div class="card-body">
                      <div class="card-body-icon">
                        <i class="fa fa-fw fa-cubes"></i>
                      </div>
                      <h6 class="card-title"><a class="card-link text-top-100" href="#">Questionnaire System</a></h6>
                    </div>
                    <div class="card-footer text-white clearfix small">

                      <!-- btn footter left -->
                      <span class="float-left">
                        <!-- emty -->
                      </span>

                      <!-- btn footer right -->
                      <span class="float-right">
                        <div class="btn-group">
                          <button type="button" class="btn btn-success icon-circle dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"></button>
                          <div class="dropdown-menu" style="z-index:3!important;">
                            <a class="dropdown-item" href="#"><i class="fa fa-fw fa-plus"></i> New Task</a>
                            <a class="dropdown-item" href="#"><i class="fa fa-fw fa-edit"></i> Edit</a>
                            <a class="dropdown-item" href="#"><i class="fa fa-fw fa-trash"></i> Delete</a>
                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item" href="#"><i class="fa fa-fw fa-info-circle"></i> More Detail</a>
                          </div>
                        </div>
                      </span>

                      <span class="float-right tab5px">
                        <div class="btn-group">
                          <button type="button" class=" btn btn-info icon-circle" data-toggle="popover" data-trigger="focus" title="Project Detail" data-content="And here's some amazing content.">
                            <i class="fa fa-fw fa-info"></i>
                          </button>
                        </div>
                      </span>

                    </div>
                  </div>
                </div>
                <!-- /.Card -->                  <!-- Card -->
                <div class="col-xl-4 col-sm-6 mb-3 small">
                  <div class="card text-white bg-primary o-hidden h-100">
                    <div class="card-body">
                      <div class="card-body-icon">
                        <i class="fa fa-fw fa-cubes"></i>
                      </div>
                      <h6 class="card-title"><a class="card-link text-top-100" href="#">Questionnaire System</a></h6>
                    </div>
                    <div class="card-footer text-white clearfix small">

                      <!-- btn footter left -->
                      <span class="float-left">
                        <!-- emty -->
                      </span>

                      <!-- btn footer right -->
                      <span class="float-right">
                        <div class="btn-group">
                          <button type="button" class="btn btn-success icon-circle dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"></button>
                          <div class="dropdown-menu" style="z-index:3!important;">
                            <a class="dropdown-item" href="#"><i class="fa fa-fw fa-plus"></i> New Task</a>
                            <a class="dropdown-item" href="#"><i class="fa fa-fw fa-edit"></i> Edit</a>
                            <a class="dropdown-item" href="#"><i class="fa fa-fw fa-trash"></i> Delete</a>
                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item" href="#"><i class="fa fa-fw fa-info-circle"></i> More Detail</a>
                          </div>
                        </div>
                      </span>

                      <span class="float-right tab5px">
                        <div class="btn-group">
                          <button type="button" class=" btn btn-info icon-circle" data-toggle="popover" data-trigger="focus" title="Project Detail" data-content="And here's some amazing content.">
                            <i class="fa fa-fw fa-info"></i>
                          </button>
                        </div>
                      </span>

                    </div>
                  </div>
                </div>
                <!-- /.Card -->                  <!-- Card -->
                <div class="col-xl-4 col-sm-6 mb-3 small">
                  <div class="card text-white bg-primary o-hidden h-100">
                    <div class="card-body">
                      <div class="card-body-icon">
                        <i class="fa fa-fw fa-cubes"></i>
                      </div>
                      <h6 class="card-title"><a class="card-link text-top-100" href="#">Questionnaire System</a></h6>
                    </div>
                    <div class="card-footer text-white clearfix small">

                      <!-- btn footter left -->
                      <span class="float-left">
                        <!-- emty -->
                      </span>

                      <!-- btn footer right -->
                      <span class="float-right">
                        <div class="btn-group">
                          <button type="button" class="btn btn-success icon-circle dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"></button>
                          <div class="dropdown-menu" style="z-index:3!important;">
                            <a class="dropdown-item" href="#"><i class="fa fa-fw fa-plus"></i> New Task</a>
                            <a class="dropdown-item" href="#"><i class="fa fa-fw fa-edit"></i> Edit</a>
                            <a class="dropdown-item" href="#"><i class="fa fa-fw fa-trash"></i> Delete</a>
                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item" href="#"><i class="fa fa-fw fa-info-circle"></i> More Detail</a>
                          </div>
                        </div>
                      </span>

                      <span class="float-right tab5px">
                        <div class="btn-group">
                          <button type="button" class=" btn btn-info icon-circle" data-toggle="popover" data-trigger="focus" title="Project Detail" data-content="And here's some amazing content.">
                            <i class="fa fa-fw fa-info"></i>
                          </button>
                        </div>
                      </span>

                    </div>
                  </div>
                </div>
                <!-- /.Card -->                  <!-- Card -->
                <div class="col-xl-4 col-sm-6 mb-3 small">
                  <div class="card text-white bg-primary o-hidden h-100">
                    <div class="card-body">
                      <div class="card-body-icon">
                        <i class="fa fa-fw fa-cubes"></i>
                      </div>
                      <h6 class="card-title"><a class="card-link text-top-100" href="#">Questionnaire System</a></h6>
                    </div>
                    <div class="card-footer text-white clearfix small">

                      <!-- btn footter left -->
                      <span class="float-left">
                        <!-- emty -->
                      </span>

                      <!-- btn footer right -->
                      <span class="float-right">
                        <div class="btn-group">
                          <button type="button" class="btn btn-success icon-circle dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"></button>
                          <div class="dropdown-menu" style="z-index:3!important;">
                            <a class="dropdown-item" href="#"><i class="fa fa-fw fa-plus"></i> New Task</a>
                            <a class="dropdown-item" href="#"><i class="fa fa-fw fa-edit"></i> Edit</a>
                            <a class="dropdown-item" href="#"><i class="fa fa-fw fa-trash"></i> Delete</a>
                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item" href="#"><i class="fa fa-fw fa-info-circle"></i> More Detail</a>
                          </div>
                        </div>
                      </span>

                      <span class="float-right tab5px">
                        <div class="btn-group">
                          <button type="button" class=" btn btn-info icon-circle" data-toggle="popover" data-trigger="focus" title="Project Detail" data-content="And here's some amazing content.">
                            <i class="fa fa-fw fa-info"></i>
                          </button>
                        </div>
                      </span>

                    </div>
                  </div>
                </div>
                <!-- /.Card -->                  <!-- Card -->
                <div class="col-xl-4 col-sm-6 mb-3 small">
                  <div class="card text-white bg-primary o-hidden h-100">
                    <div class="card-body">
                      <div class="card-body-icon">
                        <i class="fa fa-fw fa-cubes"></i>
                      </div>
                      <h6 class="card-title"><a class="card-link text-top-100" href="#">Questionnaire System</a></h6>
                    </div>
                    <div class="card-footer text-white clearfix small">

                      <!-- btn footter left -->
                      <span class="float-left">
                        <!-- emty -->
                      </span>

                      <!-- btn footer right -->
                      <span class="float-right">
                        <div class="btn-group">
                          <button type="button" class="btn btn-success icon-circle dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"></button>
                          <div class="dropdown-menu" style="z-index:3!important;">
                            <a class="dropdown-item" href="#"><i class="fa fa-fw fa-plus"></i> New Task</a>
                            <a class="dropdown-item" href="#"><i class="fa fa-fw fa-edit"></i> Edit</a>
                            <a class="dropdown-item" href="#"><i class="fa fa-fw fa-trash"></i> Delete</a>
                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item" href="#"><i class="fa fa-fw fa-info-circle"></i> More Detail</a>
                          </div>
                        </div>
                      </span>

                      <span class="float-right tab5px">
                        <div class="btn-group">
                          <button type="button" class=" btn btn-info icon-circle" data-toggle="popover" data-trigger="focus" title="Project Detail" data-content="And here's some amazing content.">
                            <i class="fa fa-fw fa-info"></i>
                          </button>
                        </div>
                      </span>

                    </div>
                  </div>
                </div>
                <!-- /.Card -->
              </div>
            </div>
          </div>
        </div>
        <!-- /.Card Layout -->

        <!-- Left Layout -->
        <div id="filter" class="col-md-3 col-sm-12 order-md-2 order-sm-2 order-1 d-none d-sm-block">

          <!-- sort layout -->
          <div class="card mb-3">
            <div class="card-header">
              <i class="fa fa-sort"></i> Sort
            </div>
            <div class="card-body">
              <div class="form-group">
                <!-- <label class="control-label" for="input-status">Status</label> -->
                <select name="filter_status" id="input-status" class="form-control">
                  <option value="">Choose your view</option>
                  <option value="1">List</option>
                  <option value="0">Title</option>
                </select>
              </div>
            </div>
          </div>
          <!-- /.sort layout -->

          <!-- Filter layout -->
          <div class="card">
            <div class="card-header">
              <i class="fa fa-filter"></i> Filter</h3>
            </div>
            <div class="card-body">
              <div class="form-group">
                <label class="control-label" for="input-model">Project Name</label>
                <input type="text" name="filter_model" value="" placeholder="Project Name" id="input-model" class="form-control" autocomplete="off"><ul class="dropdown-menu"></ul>
              </div>
              <div class="form-group text-right">
                <button type="button" class="btn btn-secondary">Filter</button>
              </div>
            </div>
          </div>
          <!-- /.Filter layout -->
        </div>
        <!-- /.Left Layout -->

      </div>
    </div>
    <!-- /.container-fluid-->

    <!-- Footer -->
    <footer class="sticky-footer">
      <div class="container">
        <div class="text-center">
          <small>Copyright © Your Website 2017</small>
        </div>
      </div>
    </footer>
    <!-- /.Footer -->

    <!-- Scroll to Top Button-->
    <a class="scroll-to-top rounded" href="#page-top"><i class="fa fa-angle-up"></i></a>
    <!-- /.Scroll to Top Butto-->

    <!-- Logout Modal-->
    <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLabel">Ready to Leave?</h5>
            <button class="close" type="button" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">×</span>
            </button>
          </div>
          <div class="modal-body">Select "Logout" below if you are ready to end your current session.</div>
          <div class="modal-footer">
            <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
            <a class="btn btn-primary" href="login.html">Logout</a>
          </div>
        </div>
      </div>
    </div>
    <!-- /.Logout Modal-->

    <!-- Delete Modal-->
    <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLabel">Want to delete?</h5>
            <button class="close" type="button" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">×</span>
            </button>
          </div>
          <div class="modal-body">Select "Delete" below if you are ready to delete your project.</div>
          <div class="modal-footer">
            <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
            <a class="btn btn-primary" href="">Delete</a>
          </div>
        </div>
      </div>
    </div>
    <!-- /.Delete Modal-->

    <!-- Bootstrap core JavaScript-->
    <script src="vendor/jquery/jquery.min.js"></script>
    <script src="vendor/popper/popper.min.js"></script>
    <script src="vendor/bootstrap/js/bootstrap.min.js"></script>
    <!-- Core plugin JavaScript-->
    <script src="vendor/jquery-easing/jquery.easing.min.js"></script>
    <!-- Custom scripts for all pages-->
    <script src="theme/js/sb-admin.js"></script>
    <!-- /.Bootstrap core JavaScript-->

    <script type="text/javascript">
      $(function () {
        $('[data-toggle="popover"]').popover()
      })
    </script>

  </div>
  <!-- /.content-wrapper-->
  <!-- /.End Page -->

</body>

</html>
