<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
        <title>Phalcon PHP Framework</title>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
        <link rel="shortcut icon" type="image/x-icon" href="<?php echo $this->url->get('img/favicon.ico')?>"/>
    </head>

    <body>
        <div>
        <!-- <div class="container"> -->
            <?php echo $this->getContent(); ?>
        </div>
        <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.0/jquery.min.js"></script>
        <!-- Latest compiled and minified JavaScript -->
    <!--
        <script>
        
            $(document).ready(function() {
    
                   
                    $('#savetask').click(function(){
                            var input = $("#name").val();
                            $.post(' echo  $this->url->get('task/checkDup')?>',{    
                                name: input
                            }, function(data){
                                console.log(data);
                               if(data == 0){
                                    alert("cannot save");
                               }else{
                                   alert("save it");
                               }
                            },  "json");

                           
                    });

                    function save(){
                        var input = $("#name").val();
                    }
                }); 
        </script>
        -->
        <script src="../vendor/jquery/jquery.min.js"></script>
        <script src="../vendor/jquery/checkDuplicate.js"></script>

        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    </body>
    
</html>
